### ISSUE TITLE
Documented build process works, but executable didn't run properly

### ISSUE THREAD

**Issue by sebjameswml** [LJ3D/LJGL-EXAMPLE#1]
```bash
seb@GPU3090:~/src/LJGL-EXAMPLE/build$ ./example/example 
Error: Could not open file normalSuzanne.vbo
Error: Could not open file normalSuzanne.ebo
ERROR::SHADER::FILE_NOT_SUCCESSFULLY_READ
ERROR::SHADER::PROGRAM::LINKING_FAILED
Vertex info
-----------
(0) : error C5145: must write to gl_Position

ERR: Failed to load texture cpp.png
^C
seb@GPU3090:~/src/LJGL-EXAMPLE/build$ 
```
When I cd into ./example and run 
```
./example
```
The program loads normalSuzanne.vbo/ebo and brings up a window with some content, though the contents look a bit weird - i.e. not like your Suzanne model

**Comment by lucianjames** [comment]
Its because you're running the `example` executable from the build directory, instead of the example directory.
The GLSL and model files are loaded in a basic way which wont work if the current directory doesnt contain them
```c++
suzannes.readVBO("normalSuzanne.vbo");
suzannes.readEBO("normalSuzanne.ebo");
suzannes.m_shader.createShader("GLSL/shader.vert.glsl", "GLSL/shader.frag.glsl");
```

**Comment by lucianjames** [comment]
And as for when it's run in the example directory, the "weirdness" you see is probably the fact it's placing the camera inside a cube of lots of Suzannes, use WASD to move out of it :)

**Comment by lucianjames** [comment]
![image](https://user-images.githubusercontent.com/65134690/234818118-c154d0e8-d4f5-43d5-a4b0-1a132e3e388d.png)

**Comment by optseb** [comment]
Ok. The trick is to press 's' for long enough that you come out of the cube.

I'd put this info into your README:

```
...
cd example/   # you have to run the example program from inside this dir
./example       # Run the example
# Now you can use wasd to move around; start with holding 's' to move out of the cube made up of Suzannas
```

**Comment by lucianjames** [comment]
Updated readme in 347d138b67cdb66bffb368f53200d3af0ee656be
